apiVersion: v1
kind: Pod
metadata:
  name: compute-node
spec:
  containers:
  - image: 192.168.24.1:8787/compute-node:latest
    name: compute-node
    securityContext:
      privileged: true
  nodeName: f12-h12-000-1029u.rdu2.scalelab.redhat.com

