apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: compute-node
  labels:
    app: compute-node
spec:
  replicas: 1000
  selector:
    matchLabels:
      app: compute-node
  template:
    metadata:
      labels:
        app: compute-node
    spec:
      containers:
      - image: 192.168.24.1:8787/sahasra-compute-node
        name: sahasra-compute-node
        securityContext:
          privileged: true

