resource_registry:
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/nic-configs/controller.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/nic-configs/compute.yaml

parameter_defaults:
  NeutronExternalNetworkBridge: "''"
  InternalApiNetCidr: 172.46.0.0/16
  TenantNetCidr: 172.47.0.0/16
  StorageNetCidr: 172.48.0.0/16
  StorageMgmtNetCidr: 172.49.0.0/16
  ManagementNetCidr: 172.50.0.0/16
  ExternalNetCidr: 172.51.0.0/16
  ControlPlaneSubnetCidr: '24'
  InternalApiAllocationPools: [{'start': '172.46.0.10', 'end': '172.46.1.254'}]
  TenantAllocationPools: [{'start': '172.47.0.10', 'end': '172.47.1.254'}]
  StorageAllocationPools: [{'start': '172.48.0.10', 'end': '172.48.1.254'}]
  StorageMgmtAllocationPools: [{'start': '172.49.0.10', 'end': '172.49.1.254'}]
  ManagementAllocationPools: [{'start': '172.50.0.10', 'end': '172.50.1.254'}]
  ExternalAllocationPools: [{'start': '172.51.0.10', 'end': '172.51.1.254'}]
  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 172.51.0.1
  #PublicVirtualFixedIPs: [{'ip_address':'172.51.0.10'}]
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.168.24.1
  # The IP address of the EC2 metadata server. Generally the IP of the Undercloud
  EC2MetadataIp: 192.168.24.1
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["10.11.5.19"]
  InternalApiNetworkVlanID: 501
  StorageNetworkVlanID: 502
  StorageMgmtNetworkVlanID: 503
  TenantNetworkVlanID: 504
  ManagementNetworkVlanID: 505
  ExternalNetworkVlanID: 10
  # Set to "br-ex" if using floating IPs on native VLAN on bridge br-ex
